version: '3'
services:
  api:
    image: ip-publisher-restful
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge